# version: '2'

# services:
#   nginx-lb:
#     image: nginxproxy/nginx-proxy
#     ports:
#       - "80:80"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#     deploy:
#       resources:
#         limits:
#           cpus: '0.10'
#           memory: 100M
#         reservations:
#           cpus: '0.01'
#           memory: 30M

#   homepage:
#     build: .
#     expose:
#       - "80"
#     environment:
#       - VIRTUAL_HOST=homepage.flyio.local
#       - VIRTUAL_PORT=80
#     deploy:
#       mode: replicated
#       replicas: 1 
#       resources: 
#         limits:
#           cpus: '0.1'
#           memory: 50M
#         reservations:
#           cpus: '0.05'
#           memory: 6M

version: '2'
name: bmt_lb
services:
  load_balancer:
    build: ./docker_file/lb_nginx
    container_name: mproxy
    ports:
      - 80:80
    depends_on:
      - homepage_1
    links:
      - homepage_1
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 10M
        reservations:
          cpus: '0.01'
          memory: 6M

  homepage_1:
    image: pysatellite/dj-twenty-six.github.io:bmt
    deploy:
      resources: 
        limits:
          cpus: '0.02'
          memory: 30M
        reservations:
          cpus: '0.01'
          memory: 6M